version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"