name: Publish Snapshot
env:
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
  ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches:
      - main
jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Publish with Gradle Wrapper
        run: ./gradlew publishMavenJavaPublicationToGitHubPackagesRepository publishMavenJavaPublicationToOSSHRRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}